INSERT INTO paises (nome) VALUES
('Estados Unidos'),
('China'),
('Grã-Bretanha'),
('Japão'),
('Alemanha'),
('França'),
('Itália'),
('Austrália'),
('Canadá'),
('Rússia'),
('Países Baixos'),
('Brasil'),
('Coreia do Sul'),
('Nova Zelândia'),
('Índia'),
('Espanha'),
('Argentina'),
('África do Sul'),
('México'),
('Ucrânia'),
('Hungria'),
('Polônia'),
('Suécia'),
('Noruega'),
('Finlândia'),
('República Tcheca'),
('Dinamarca'),
('Bélgica'),
('Turquia'),
('Israel'),
('Grécia'),
('Filipinas'),
('Portugal'),
('Cingapura'),
('Tailândia'),
('Irã'),
('Quênia'),
('Etiópia'),
('Nigéria'),
('Jamaica'),
('Cuba');

-- Inserindo modalidades olímpicas na tabela 'modalidades' sem o ID
INSERT INTO modalidades (nome) VALUES
('Atletismo'),
('Natação'),
('Ginástica Artística'),
('Futebol'),
('Basquete'),
('Vôlei'),
('Boxe'),
('Judô'),
('Tênis'),
('Ciclismo'),
('Esgrima'),
('Remo'),
('Canoagem'),
('Handebol'),
('Rugby'),
('Taekwondo'),
('Badminton'),
('Hipismo'),
('Levantamento de Peso'),
('Tiro com Arco'),
('Tiro Esportivo'),
('Pentatlo Moderno'),
('Triatlo'),
('Vela'),
('Lutas'),
('Escalada Esportiva'),
('Surfe'),
('Skate');
