INSERT INTO paises (nome) VALUES
('Estados Unidos'),
('China'),
('Grã-Bretanha'),
('Japão'),
('Alemanha'),
('França'),
('Itália'),
('Austrália'),
('Canadá'),
('Rússia'),
('Países Baixos'),
('Brasil'),
('Coreia do Sul'),
('Nova Zelândia'),
('Índia'),
('Espanha'),
('Argentina'),
('África do Sul'),
('México'),
('Ucrânia'),
('Hungria'),
('Polônia'),
('Suécia'),
('Noruega'),
('Finlândia'),
('República Tcheca'),
('Dinamarca'),
('Bélgica'),
('Turquia'),
('Israel'),
('Grécia'),
('Filipinas'),
('Portugal'),
('Cingapura'),
('Tailândia'),
('Irã'),
('Quênia'),
('Etiópia'),
('Nigéria'),
('Jamaica'),
('Cuba');
